#!/usr/bin/env bash

REGISTRY=${1:-"registry.tell.nu"}

if ! git-is-repo; then
    exit 1
fi

GIT_DIR=$(git-get-dir)

IMAGE=$(basename $GIT_DIR)

podman image ls -f "reference=$REGISTRY/$IMAGE" \
    | tail -n +2 \
    | fzf \
    | awk -F ' ' '{print $1 ":" $2}'
