#!/usr/bin/env bash

REGISTRY=${1:-"registry.tell.nu"}

if ! git-is-repo; then
    exit 1
fi

GIT_DIR=$(git-get-dir)

IMAGE=$(basename $GIT_DIR)

TAG=$(git-get-branch)

if git-is-clean; then
    TAG="${TAG}_$(git-get-short-hash)"
else
    TAG="${TAG}_dev"
fi

echo "$REGISTRY/$IMAGE:$TAG"
