#!/usr/bin/env bash

IMAGE=$1

if [[ -z "$IMAGE" ]]; then
    exit 1
fi

if ! git-is-repo; then
    exit 1
fi

cd $(git-get-dir)

if ! image-is-dockerfile; then
    exit 1
fi

if ! podman build --tag $IMAGE .; then
    pp-color red; pp-box "BUILD FAILURE | $IMAGE"; pp-color
    exit 1
fi
    
pp-color blue; pp-box "BUILD SUCCESS | $IMAGE"; pp-color
