#!/usr/bin/env bash

HOST=vm01
PCON=vm01

if [[ -z "$1" ]]; then
    exit 1
fi

LOCAL_FILE=$1

if ! REMOTE_FILE=$(ssh agent@$HOST bash -c "mktemp"); then
    exit 1
fi

if ! scp $LOCAL_FILE agent@$HOST:$REMOTE_FILE > /dev/null; then
    exit 1
fi

podman -r -c $PCON run \
    -it \
    --rm \
    --network db \
    -v $REMOTE_FILE:/commands.txt \
    --secret postgres_connection,type=env,target=CONN \
    docker.io/postgres \
    bash -c 'psql $CONN -f /commands.txt'

ssh agent@vm01 bash -c "'rm $REMOTE_FILE'"
