#!/usr/bin/env bash

TEMP_FILE=$(cat | ssh agent@vm01 'TEMP=$(mktemp); cat > $TEMP; echo $TEMP')

__cleanup ()
{
    SIGNAL=$1

    ssh agent@vm01 "rm -f $TEMP_FILE"

    if [[ -n "$SIGNAL" ]]; then
        trap $SIGNAL
        kill -${SIGNAL} $$
    fi
}

trap __cleanup EXIT

podman -r -c vm01 run \
    --rm \
    --network db \
    -v $TEMP_FILE:/commands.txt \
    --secret postgres_connection,type=env,target=PG_CONN \
    docker.io/postgres \
    bash -c 'psql $PG_CONN -q -f /commands.txt'
